---
title: "DATA CLEANUP: Sla1 initiation rates in Ede1 mutants"
date: "Last compiled on `r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    code_download: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This notebook serves only to load the .csv's generated by ImageJ and Python 
and create a unified data structure which can be then appended to the main notebook.

# Sla1 density

```{r}
library(tidyverse)
```

```{r load_density}
rm(list = ls())

strains <- read_csv("data/strain_lut.csv",
                    col_types = cols(ede1 = col_factor(NULL)))

sla1_density <- dir('data/density', pattern = 'dataset', full.names = T) %>%
  #map(dir, pattern = '.csv', full.names = T) %>%
  map(read_csv) %>%
  imap_dfr(~.x, .id = 'dataset')
```

```{r process_density}
# set pixel area; Orca pixels are 6.45um / 100x magnification 
pixel_area <- 0.0645**2

# clean up dataframe
sla1_density <- sla1_density %>%
  separate(Cell, c('date', 'strain', 'movie', 'cell', 'channel'), '_') %>% # separate filename into variables
  select(-c(channel, Threshold))%>% # remove stuff
  rename(cross_area = Cross_Area, patches = Patches) %>%
  left_join(strains, by = 'strain') %>%
  mutate(area = cross_area * 4 * pixel_area, density = patches / area)
```

```{r}
# save image
save(strains, sla1_density, file = "data/sla1_density.RData")
write_excel_csv(sla1_density, file = "data/sla1_density.csv")
```

# Sla1 lifetimes

```{r load_lifetime}
# The first dataset was acquired in 2018
# with a shorter exposure time than repeats
# Therefore it has to be processed separately
# Let's see how different it really is before we include/exclude it
# from the analysis
frame_length <- 0.23

lifetime_00 <- list.files('data/lifetime/old_exposure',
                          pattern = '.txt', full.names = T) %>%
  set_names(nm = (basename(.) %>% tools::file_path_sans_ext())) %>% # names for the map output, wthout folder or extension
  map_df(read_table2, comment = '%%', col_names = F,
           col_types = cols(), .id = 'filename') %>%
  group_by(filename) %>%
  summarise(max = max(X1), min = min(X1)) %>%
  mutate(lifetime = (max - (min - 1)) * frame_length,
         dataset = '0',
         .keep = 'unused') %>%
  separate(filename, c('date', 'strain', 'movie', 'channel', 'processing', 'cell', 'md', 'trajectory'), '_') %>%
  select(-c(channel, processing, md)) %>%
  left_join(strains, by = 'strain')
```


```{r}
frame_length <- 0.5

sla1_lifetime <- dir('data/lifetime', pattern = 'dataset', full.names = T) %>%
  map(dir, pattern = '.txt', full.names = T) %>%
  map(
    ~ set_names(.x,
                nm = (basename(.x) %>% tools::file_path_sans_ext()))) %>%
  map(
    ~ map_df(.x, read_table2,
             comment = '%%',
             col_names = F,
             col_types = cols(),
             .id = 'filename')) %>% # id observations by filename
  imap_dfr(~.x, .id = 'dataset') %>%
  group_by(filename, dataset) %>%
  summarise(max = max(X1), min = min(X1),
            .groups = 'drop') %>%
  mutate(lifetime = (max - (min - 1)) * frame_length) %>%
  select(filename, lifetime, dataset)
```

```{r process_lifetime}
# Final touches on the lifetime, separated from main calculation
sla1_lifetime <- sla1_lifetime %>%
  separate(filename, c('date', 'strain', 'movie', 'cell', 'channel', 'processing', 'md', 'trajectory'), '_') %>%
  select(-c(channel, processing, md)) %>%
  left_join(strains, by = 'strain')
```

```{r join_lifetime}
# Bind dataset 0 to the rest
sla1_lifetime <- bind_rows(sla1_lifetime, lifetime_00)
```

```{r}
# save image
save(strains, sla1_lifetime, file = "data/sla1_lifetime.RData")
write_excel_csv(sla1_lifetime, file = "data/sla1_lifetime.csv")
```
