---
title: "DATA CLEANUP: Sla1 density in Ede1∆PQCC-Syp1 fusion"
date: "Last compiled on `r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    code_download: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This notebook serves only to load the .csv's generated by ImageJ and Python 
and create a unified data structure which can be then appended to the main notebook.

```{r libs}
library(tidyverse)
```

```{r strains}
rm(list = ls())
strains <- read_csv("data/strain_lut.csv", 
                    col_types = cols(ede1 = col_factor(NULL))) # order factor levels in csv file
```

```{r load}
sla1_density <- dir('data', pattern = 'dataset', full.names = T) %>%
  #map(dir, pattern = '.csv', full.names = T) %>%
  map(read_csv) %>%
  imap_dfr(~.x, .id = 'dataset')
```

```{r process}  
# set pixel area; Orca pixels are 6.45um / 100x magnification 
pixel_area <- 0.0645**2

sla1_density <- sla1_density %>%
  separate(Cell, c('date', 'strain', 'movie', 'cell', 'channel'), '_') %>% # separate filename into variables
  select(-c(channel, Threshold))%>% # remove stuff
  rename(cross_area = Cross_Area, patches = Patches) %>%
  mutate(area = cross_area * 4 * pixel_area, density = patches / area) %>%
  left_join(strains, by = 'strain')
```

```{r save}
# save image
write_excel_csv(format.data.frame(sla1_density, digits = 3),
                'data/syp1_fusion_sla1.csv')
save(sla1_density, strains, file = 'data/syp1_fusion_sla1.RData')
```
