---
title: "DATA CLEANUP: Ede1 Gal induction"
date: "Last compiled on `r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    code_download: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This notebook serves only to load the .csv's generated by ImageJ and create a unified data structure which can be then appended to the main notebook.

```{r}
library(tidyverse)
```

```{r process}
rm(list = ls())
intensities <- list.files("data/imagej/", pattern = '.csv' , full.names = TRUE ) %>%
  set_names(nm = (basename(.) %>% tools::file_path_sans_ext())) %>% # names for the map output, wthout foder or extension
  map_df(read_csv,
         col_types = cols(), # this doesn't do anything but suppresses the column spec message
         col_names = c('frame', 'intensity'), # set up names
         skip = 1, # skip the ImageJ header
         .id = "filename") %>% # id observations by filename
  separate(filename, c('date', 'strain', 'movie', 'channel', 'processing', 'position', 'signal'), '_') %>%
  mutate(time = frame * 5 + 10) %>% # imaging started ~15 minutes after galactose addition
  select(signal, movie, position, time, intensity)
```

```{r}
write_excel_csv(intensities, 'data/ede1_gal_induction.csv')
```
