---
title: "DATA CLEANUP: Ede1 intensity comparison for 3∆ and OE strains"
date: "Last compiled on `r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    code_download: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This notebook serves only to load the .csv's generated by ImageJ and Python and create a unified data structure which can be then appended to the main notebook.

```{r}
library(tidyverse)
```

```{r load_cyto}
rm(list = ls())

cyto_full <- dir('data/cyto', pattern = 'dataset', full.names = T) %>%
  map(dir, pattern = '.csv', full.names = T) %>%
  map(
    ~ set_names(.x,
                nm = (basename(.x) %>% tools::file_path_sans_ext()))) %>%
  map(
    ~ map_df(.x, read_csv,
         col_types = cols(), # suppress the column spec message
         col_names = c('frame', 'intensity'), # set up names
         skip = 1, # skip the ImageJ header
         .id = "filename")) %>% # id observations by filename
  imap_dfr(~.x, .id = 'dataset') %>%
  select(-frame) %>%
  separate(filename, c('date', 'strain', 'image', 'channel', 'processing', 'window'), '_')
```

```{r load_cell}
cell_full <- dir('data/cell', pattern = 'dataset', full.names = T) %>%
  map(read_csv, col_types = cols()) %>%
  imap_dfr(~.x, .id = 'dataset') %>%
  separate(cell, c('date', 'strain', 'image', 'window', 'channel', 'processing'), '_') %>%
  rename(int_mean = mean, int_median = median, int_sd = sd)
```

```{r}
save.image('data/data_full.RData')
```

```{r}
cyto <- cyto_full %>%
  select(date, strain, image, window, intensity, dataset) %>%
  tibble(., localization = 'Cytosolic')

cell <- cell_full %>%
  rename(intensity = int_mean) %>%
  select(date, strain, image, window, intensity, dataset) %>%
  tibble(., localization = 'Cellular')

strains <- read_csv("data/strain_lut.csv", 
                    col_types = cols(nickname = col_factor(NULL)))

intensities <- bind_rows(cyto, cell) %>%
  left_join(strains, by = 'strain') %>%
  mutate(strain = nickname,
         localization = recode_factor(localization,
                                      'Cellular' = 'Cellular',
                                      'Cytosolic' = 'Cytosolic'),
         .keep = 'unused') %>%
  select(-mCherry)


save(list = c('strains', 'intensities'), file = 'data/data_clean.RData')
write_excel_csv(intensities, file = 'data/intensities.csv')
```
